Spring Boot Data JPA
Someboty/bookShop pull request #3
Opened 2023-09-05 22:04 UTC by Someboty

Replacement of existing BookRepository with a JpaRepostory interface (removed BookRepositoryImpl, changed BookRepository), added Liquibase support (db.changelog-master.yaml, 01-create-books-table.yaml, changes in pom.xml, validate in application.properties), added more annotations in Book, replaced @Data by @getter and @Setter. Added soft delete of Book, added updateBookById on all levels, added search method, specification providers, specification interfaces and implementations.

2023-09-05 23:21 UTC, Skarbey approved these changes
Seems nice to me. Great work

2023-09-06 15:34 UTC, vovasalyha requested changes
GJ. Left few suggestions.

2023-09-06 15:34 UTC, vovasalyha commented on src/main/java/com/bookshop/model/Book.java
>  public class Book {
Overriding equals and hashcode for entities is also a good practice.

2023-09-06 15:34 UTC, vovasalyha commented on src/main/java/com/bookshop/repository/book/BookSpecificationBuilder.java
> +        if (bookSearchParameters.titles() != null
You are using the same code `bookSearchParameters.titles() != null && bookSearchParameters.titles().length > 0` for several if statements, for me it's a good candidate for private method.

2023-09-06 15:34 UTC, vovasalyha commented on src/main/java/com/bookshop/repository/book/BookSpecificationProviderManager.java
> +                    () -> new RuntimeException("Can't find specification provider by key " + key)
better throw `NoSuchElement`

2023-09-06 15:34 UTC, vovasalyha commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +    public BookDto update(Long id, CreateBookRequestDto requestDto) {
Usually it's safer to fetch the entity before update

2023-09-06 20:12 UTC, Someboty commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +    public BookDto update(Long id, CreateBookRequestDto requestDto) {
Added getById(id) to ensure entity is present

2023-09-06 20:13 UTC, Someboty commented on src/main/java/com/bookshop/model/Book.java
>  public class Book {
Replaced @Getter and @Setter to @Data (back)

2023-09-08 15:31 UTC, vovasalyha approved these changes
GJ.

2023-09-08 15:31 UTC, vovasalyha commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +    public BookDto update(Long id, CreateBookRequestDto requestDto) {
You can do it even more elegant and in OOP style. Instead of creating a new book object from updated fields. You can assign `getById` call to a variable and set new fields to the fetched entity, then save it :)

2023-09-09 12:37 UTC, merged